import { Link } from 'react-router-dom'
import Icon from '../components/common/Icon'

const tools = [
  { title: 'Understand anything', text: 'Work through tricky concepts with an AI study companion.', icon: 'chat', label: 'Start a conversation', to: '/study', tone: 'mint' },
  { title: 'Your knowledge, organized', text: 'Bring your notes and documents together. Find the important bits.', icon: 'book', label: 'Explore your library', to: '/library', tone: 'peach' },
  { title: 'Turn practice into progress', text: 'Put your knowledge to the test with step-by-step problems.', icon: 'practice', label: 'Try a practice problem', to: '/practice', tone: 'lilac' },
]
export default function Home() {
  const date = new Intl.DateTimeFormat('en', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date())
  return <div className="dashboard">
    <div className="dashboard-heading"><div><div className="eyebrow">A LITTLE CURIOSITY GOES A LONG WAY</div><h1>Make room for your next <em>aha.</em></h1><p>Your ideas, your pace. Let’s make learning feel a little lighter.</p></div><span className="date-label"><Icon name="clock" size={16} />{date}</span></div>
    <section className="hero-panel" aria-labelledby="hero-title">
      <div className="hero-copy"><span className="hero-badge"><Icon name="sparkle" size={15} /> YOUR PERSONAL LEARNING COMPANION</span><h2 id="hero-title">Big questions.<br />Brighter understanding.</h2><p>Untangle a concept, make sense of your notes, or explore something new. You don’t have to figure it all out alone.</p><div className="hero-actions"><Link className="primary-action" to="/study">Start studying <Icon name="arrow" size={18} /></Link><Link className="secondary-action" to="/library"><Icon name="upload" size={17} /> Upload your notes</Link></div><div className="hero-footnote"><Icon name="check" size={15} /> Learn at your own pace, one question at a time.</div></div>
      <div className="learning-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="art-star star-one">✦</span><span className="art-star star-two">✧</span><div className="floating-label"><span className="mini-check"><Icon name="check" size={13} /></span> A little clearer. A lot more confident.</div><div className="art-card card-back" /><div className="art-card card-front"><div className="art-card-heading"><span><Icon name="sparkle" size={20} /></span>THE LEARNING PROCESS</div><div className="art-card-title">Connect the dots.</div><div className="concept-map"><span className="concept concept-a">Ask</span><span className="concept concept-b">Explore</span><span className="concept concept-c">Understand</span><i className="connector connector-a" /><i className="connector connector-b" /></div><div className="art-lines"><i /><i /><i /></div><div className="art-card-footer"><span className="mini-check"><Icon name="check" size={12} /></span> A new perspective unlocked</div></div><div className="idea-tag"><Icon name="practice" size={17} /> That aha! feeling</div></div>
    </section>
    <section className="tools-section" aria-labelledby="tools-title"><div className="section-heading"><div><h2 id="tools-title">A toolkit for your curious mind</h2><p>Pick a starting point. We’ll help with the rest.</p></div><span className="section-kicker">LESS FRICTION. MORE LEARNING.</span></div><div className="tool-grid">{tools.map(tool => <Link to={tool.to} className={`tool-card ${tool.tone}`} key={tool.title}><div className="tool-top"><span className="tool-icon"><Icon name={tool.icon} size={23} /></span><Icon name="arrow" size={19} /></div><h3>{tool.title}</h3><p>{tool.text}</p><span className="tool-link">{tool.label}<Icon name="arrow" size={16} /></span></Link>)}</div></section>
    <div className="dashboard-bottom"><section className="getting-started"><div className="section-heading"><h2>A good place to begin</h2><span className="small-pill">YOUR FIRST STEPS</span></div><Link className="step-row" to="/library"><span className="step-number">01</span><div><h3>Bring your learning materials</h3><p>Upload a document or a set of notes to your library.</p></div><Icon name="arrow" size={19} /></Link><Link className="step-row" to="/study"><span className="step-number">02</span><div><h3>Follow your curiosity</h3><p>Ask a question, break down a topic, or get a fresh explanation.</p></div><Icon name="arrow" size={19} /></Link></section><section className="insight-card"><span className="insight-label"><Icon name="chart" size={18} /> THE BIGGER PICTURE</span><h2>Small steps.<br />Meaningful progress.</h2><p>Reflect on what you’re learning and discover where to focus next.</p><Link to="/analytics">Explore learning insights <Icon name="arrow" size={17} /></Link></section></div>
  </div>
}
